services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: /modpack/modpack.zip
      MEMORY: "8G"
      OPS: "JustTheWise"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      ONLINE_MODE: "true"
    volumes:
      - mc_data:/data
      - mc_modpack:/modpack
      - ./modpack:/modpack_src # zip dans ton repo
    entrypoint: >
      sh -c "cp -n /modpack_src/modpack.zip /modpack/ &&
             exec /start"  # lance le script officiel après copie
volumes:
  mc_data:
  mc_modpack:
