services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: ${MODPACK_URL}
      MEMORY: "8G"
      OPS: "JustTheWise"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      ONLINE_MODE: "true"
    volumes:
      - mc_data:/data
      - mc_modpack:/modpack
volumes:
  mc_data:
  mc_modpack:
