services:
  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: ${CF_API_KEY}
      CF_SERVER_MOD: /modpack/modpack.zip
      MEMORY: "8G"
      OPS: "JustTheWise"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      ONLINE_MODE: "true"
    volumes:
      - mc_data:/data
      - mc_modpack:/modpack
    entrypoint: >
      sh -c "
        if [ ! -f /modpack/modpack.zip ]; then
          echo 'Téléchargement du modpack...';
          curl -L -o /modpack/modpack.zip ${MODPACK_URL};
        fi;
        exec /start
      "
volumes:
  mc_data:
  mc_modpack:
